services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: >
      sh -c "
        npx typeorm-ts-node-esm migration:run --dataSource src/config/ormconfig.ts &&
        node dist/main.js
      "

volumes:
  pgdata:
